# Generated by Django 3.1.7 on 2021-02-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('institution', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('monthStart', models.CharField(blank=True, max_length=3, null=True)),
                ('yearStart', models.CharField(blank=True, max_length=4, null=True)),
                ('monthEnd', models.CharField(blank=True, max_length=3, null=True)),
                ('yearEnd', models.CharField(max_length=4)),
            ],
        ),
    ]
