# Generated by Django 3.1.7 on 2021-03-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='monthEnd',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='experience',
            name='monthStart',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='experience',
            name='yearStart',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
