# Generated by Django 3.1.7 on 2021-03-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_auto_20210321_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='yearEnd',
            field=models.CharField(max_length=5),
        ),
    ]
