# Generated by Django 3.1.7 on 2021-02-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(blank=True, choices=[('University', 'University'), ('High School', 'High School'), ('technical', 'technical'), ('WorkShop', 'WorkShop'), ('Otro', 'Otro')], max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('remark', models.CharField(blank=True, max_length=50, null=True)),
                ('institution', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('monthStart', models.CharField(blank=True, max_length=3, null=True)),
                ('yearStart', models.CharField(blank=True, max_length=4, null=True)),
                ('monthEnd', models.CharField(blank=True, max_length=3, null=True)),
                ('yearEnd', models.CharField(blank=True, max_length=4, null=True)),
                ('finish', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('En Curso', 'En Curso')], max_length=100, null=True)),
            ],
        ),
    ]
