# Generated by Django 3.1.7 on 2021-02-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studie',
            name='kind',
            field=models.CharField(blank=True, choices=[('University', 'University'), ('High School', 'High School'), ('Technical', 'Technical'), ('WorkShop', 'WorkShop'), ('Self', 'Self'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
