# Generated by Django 3.1.7 on 2021-02-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_auto_20210220_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studie',
            name='monthEnd',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='studie',
            name='monthStart',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='studie',
            name='yearStart',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
