# Generated by Django 3.1.7 on 2021-02-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_auto_20210220_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studie',
            name='yearEnd',
            field=models.CharField(max_length=4),
        ),
    ]
