# Generated by Django 3.1.7 on 2021-02-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0005_auto_20210220_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studie',
            name='finish',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('En Curso', 'En Curso')], default='Yes', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studie',
            name='institution',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studie',
            name='kind',
            field=models.CharField(blank=True, choices=[('University', 'University'), ('High School', 'High School'), ('Technical', 'Technical'), ('WorkShop', 'WorkShop'), ('Self', 'Self'), ('Other', 'Other')], default='Other', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studie',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='studie',
            name='remark',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
    ]
