# Generated by Django 3.1.7 on 2021-03-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0007_auto_20210220_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studie',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studie',
            name='monthEnd',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='studie',
            name='monthStart',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='studie',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studie',
            name='yearStart',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
