# Generated by Django 3.1.7 on 2021-04-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0010_auto_20210321_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studie',
            name='finish',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=100),
        ),
    ]
