# Generated by Django 3.1.7 on 2021-02-21 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='Dominium',
            new_name='dominium',
        ),
    ]
